Repository puppetlabs/prm, pull requests merged in 2021-12, with the labels that each got.

#33 (GH-8) PRM exec
  .vscode/launch.json
  build.ps1
  build.sh
  cmd/exec/exec.go
  cmd/exec/exec_test.go
  go.mod
  go.sum
  internal/pkg/utils/utils.go
  main.go
  pkg/prm/config.go
  pkg/prm/config_test.go
  pkg/prm/exec.go
  pkg/prm/prm.go
  pkg/prm/prm_test.go
  pkg/prm/tool.go
Labels: enhancement

#37 (GH-36) Fix NPE when puppet version unset in cfg on disk
  pkg/prm/config.go
Labels: bug

#39 (GH-28) Add acceptance tests for `prm set|get`
  .github/workflows/acceptance.yml
  acceptance/get/get_test.go
  acceptance/set/set_test.go
  cmd/root/root.go
  go.mod
  go.sum
Labels: maintenance

#48 (maint) Move runningConfig into PRM object
  cmd/exec/exec.go
  cmd/exec/exec_test.go
  cmd/get/backend.go
  cmd/get/get.go
  cmd/get/get_test.go
  cmd/get/puppet.go
  cmd/root/root.go
  main.go
  pkg/prm/config.go
  pkg/prm/config_test.go
  pkg/prm/prm.go
Labels: maintenance

#60 (maint) Build CMD properly
  pkg/prm/docker.go
Labels: maintenance

#64 (GH-63) Allow additional tool args to be set within validate.yml
  cmd/exec/exec.go
  go.mod
  go.sum
  pkg/prm/docker.go
  pkg/prm/exec.go
  pkg/prm/prm.go
  pkg/prm/tool_groups.go
Labels: enhancement

#67 (MAINT) Adjust status accept tests to use siloed cfg
  acceptance/status/status_test.go
Labels: maintenance

#65 (MAINT) Rename tools dir to scripts; Update references
  .github/workflows/installation.yml
  scripts/install.ps1
  scripts/install.sh
Labels: maintenance

#76 (GH-75) Created docs site scripts
  .gitignore
  README.md
  docs.ps1
  docs.sh
Labels: maintenance

#77 (GH-51) Improve `prm exec` error
  pkg/prm/prm.go
Labels: maintenance
